---
- name: Install Grafana
  block:
    - name: Install Grafana on CentOS
      when: ansible_os_family == "RedHat"
      ansible.builtin.yum:
        name: "grafana-{{ grafana_version }}"
        state: present

    - name: Install Grafana on Ubuntu
      when: ansible_os_family == "Debian"
      ansible.builtin.apt:
        name: "grafana"
        state: present
        update_cache: yes
