---
- name: Install Prometheus
  block:
    - name: Install Prometheus on CentOS
      when: ansible_os_family == "RedHat"
      ansible.builtin.yum:
        name: "prometheus-{{ prometheus_version }}"
        state: present

    - name: Install Prometheus on Ubuntu
      when: ansible_os_family == "Debian"
      ansible.builtin.apt:
        name: "prometheus"
        state: present
        update_cache: yes
